export const CREATE_CHAPTER_REQUEST = 'CHAPTER_CREATE_REQUEST'
export const CREATE_CHAPTER_SUCCESS = 'CHAPTER_CREATE_SUCCESS'
export const CREATE_CHAPTER_FAILURE = 'CHAPTER_CREATE_FAILURE'

export const CHANGE_CHAPTER_NAME_REQUEST = 'CHANGE_CHAPTER_NAME_REQUEST'
export const CHANGE_CHAPTER_NAME_SUCCESS = 'CHANGE_CHAPTER_NAME_SUCCESS'
export const CHANGE_CHAPTER_NAME_FAILURE = 'CHANGE_CHAPTER_NAME_FAILURE'