export const CREATE_CHAPTER_REQUEST = 'CHAPTER_CREATE_REQUEST'
export const CREATE_CHAPTER_SUCCESS = 'CHAPTER_CREATE_SUCCESS'
export const CREATE_CHAPTER_FAILURE = 'CHAPTER_CREATE_FAILURE'

export const CHANGE_CHAPTER_NAME_REQUEST = 'CHANGE_CHAPTER_NAME_REQUEST'
export const CHANGE_CHAPTER_NAME_SUCCESS = 'CHANGE_CHAPTER_NAME_SUCCESS'
export const CHANGE_CHAPTER_NAME_FAILURE = 'CHANGE_CHAPTER_NAME_FAILURE'

export const FETCH_CHAPTER_REQUEST = 'FETCH_CHAPTER_REQUEST'
export const FETCH_CHAPTER_SUCCESS = 'FETCH_CHAPTER_SUCCESS'
export const FETCH_CHAPTER_FAILURE = 'FETCH_CHAPTER_FAILURE'